### ISSUE TITLE
integerate this with the new jupyterlab

### ISSUE THREAD

**Issue by shelper** [minodes/pynb#1]
would be much useful and powerful...

**Comment by elehcimd** [comment]
Yes indeed! What would you expect from such an integration? A few more actions in the menu "Import from Python Notebook" and "export from Python Notebook"?

**Comment by shelper** [comment]
i was thinking of that a markdown file with python code blocks that can be edited in jupyterlab text editor. can be sent to ipython shell for execution,
actually current jupyterlab already has this support, what it lacks of is
1. syntax highlighting
2. autocompletion.

refer to [this](https://github.com/jupyterlab/jupyterlab/issues/3340)

**Comment by elehcimd** [comment]
What you propose is to substitute the JSON format of notebooks with Markdown. It might help with version control but keep in mind that images would be stored in separate files, complicating things. Besides this, all other drawbacks that PyNb tries to mitigate would remain unresolved.

**Comment by shelper** [comment]
understood, i still think there is value to use markdown to replace notebook, the editing could be a more seamless flow, can be an option for some use cases, just like the org-mode in Emacs. 

i used to use org-mode for such use case, and i felt it is a much better way for scientific research where lots of explanation text mixed with code blocks. I am looking for a similar way in jupyter as Emacs is not as user friendly as jupyterlab ...

**Comment by elehcimd** [comment]
It would be an extension of Jupyter lab, with nearly zero overlap with PyNb besides borrowing some ideas :)
